name: Pull Request - Test and Validate

env:
  PYTHON_VERSION: 3.11

permissions:
  contents: read # access to check out code and install dependencies

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up python with relevant version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.2.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Load cached venv (if cache hit)
        id: cached-poetry-dependencies
        uses: actions/cache/restore@v3
        with:
          path: .venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies with poetry
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-root --with dev

      - name: Cache poetry environment if cache was missed
        uses: actions/cache/save@v3
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        id: cache_poetry_environment
        with:
          path: .venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Run test suite and report coverage
        # For now we won't have a CI requirement for coverage, but should aim for 100%, 95% as minimum
        run: |
          source .venv/bin/activate
          pytest tests/
